id = "tengo"
name = "Tengo"
version = "0.1.6"
schema_version = 1
description = "Tengo language support for Zed."
repository = "https://github.com/popoffvg/zed-tengo"
authors = ["Vitalii Popov <popoffvg@gmail.com>"]
languages = ["languages/tengo"]

[grammars.tengo]
repository = "https://github.com/popoffvg/tree-sitter-tengo"
rev = "0184f5bc04e3e9999ae1394612d2ee6495102fec"

[language_servers.tengo-lsp]
name = "Tengo LSP"
languages = ["Tengo"]
